### ISSUE TITLE
大佬，无框架实现里的主程序运行报KeyError: 'formatters'，

### ISSUE THREAD

**Issue by Black-Spider-Man** [yangwohenmai/LSTM#9]
尝试做了log更改 没解决

**Comment by yangwohenmai** [comment]
> 尝试做了log更改 没解决

能否定位到哪行代码出错

**Comment by yuanhs1996** [comment]
大佬，有出博客或者视频教程吗，麻烦放个链接

**Comment by LJD20000611** [comment]
ModuleNotFoundError: No module named 'tensorflow.compat'

**Comment by retoreQAQ** [comment]
> > 尝试做了log更改 没解决
> 
> 能否定位到哪行代码出错

Traceback (most recent call last):
  File "d:\workspace\LSTM-master\LSTM无框架源码实现\src\scenario_seqCurve.py", line 30, in <module>
    logging.config.fileConfig(log_conf)
  File "C:\Users\80543\AppData\Local\Programs\Python\Python38-32\lib\logging\config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "C:\Users\80543\AppData\Local\Programs\Python\Python38-32\lib\logging\config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "C:\Users\80543\AppData\Local\Programs\Python\Python38-32\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

遇到了一样的问题

**Comment by yangwohenmai** [comment]
> > > 尝试做了log更改 没解决
> > 
> > 
> > 能否定位到哪行代码出错
> 
> Traceback (most recent call last): File "d:\workspace\LSTM-master\LSTM无框架源码实现\src\scenario_seqCurve.py", line 30, in logging.config.fileConfig(log_conf) File "C:\Users\80543\AppData\Local\Programs\Python\Python38-32\lib\logging\config.py", line 71, in fileConfig formatters = _create_formatters(cp) File "C:\Users\80543\AppData\Local\Programs\Python\Python38-32\lib\logging\config.py", line 104, in _create_formatters flist = cp["formatters"]["keys"] File "C:\Users\80543\AppData\Local\Programs\Python\Python38-32\lib\configparser.py", line 960, in **getitem** raise KeyError(key) KeyError: 'formatters'
> 
> 遇到了一样的问题

直接把日志注释掉，不是必须要有的

**Comment by retoreQAQ** [comment]
> 

谢谢回答，logger模块都注释掉后有新的报错：
File "D:\workspace\LSTM-master\LSTM无框架源码实现\src\scenario_seqCurve.py", line 318, in main_rnn
    y, loss_v,_,result = sess.validation(x_v, y_v[:,:,0])
  File "D:\workspace\LSTM-master\LSTM无框架源码实现\src\scenario_seqCurve.py", line 327, in <module>
    main_rnn()
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

我看了下这个y_v应该是在126行
testY = np.array(yArray[Params.TRAINING_EXAMPLES:])
这里赋值，但是此处生成的是一个一维数组，而非三维数组，是否应该进行reshape呢？

**Comment by yangwohenmai** [comment]
> > 
> 
> 谢谢回答，logger模块都注释掉后有新的报错： File "D:\workspace\LSTM-master\LSTM无框架源码实现\src\scenario_seqCurve.py", line 318, in main_rnn y, loss_v,_,result = sess.validation(x_v, y_v[:,:,0]) File "D:\workspace\LSTM-master\LSTM无框架源码实现\src\scenario_seqCurve.py", line 327, in main_rnn() IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
> 
> 我看了下这个y_v应该是在126行 testY = np.array(yArray[Params.TRAINING_EXAMPLES:]) 这里赋值，但是此处生成的是一个一维数组，而非三维数组，是否应该进行reshape呢？

这个地方其实不重要，这里的数据主要是为了后面画展示图用的。模型训练和预测过程前面已经运行完了。这个报错具体的问题应该是y_v[:,:,0]的取值方式可能不对，我映像中y_v可能是个shape=(1,1,1)的结构，所以用了y_v[:,:,0]这种取值方式，你可以根据y_v的实际shape调整一下取值方法
